### PR TITLE
Math React Components

### PR DESCRIPTION
**Pull request by Chimoneg27**
### For this feature I did the following

- Removed linter errors
- Created the components directory with a Calculator.js file
- Made use of gitflow
- Used functional components
- Made child components

**URGENT NOTICE. HELP**

- I keep on getting this error "ESLint couldn't find the plugin "eslint-plugin-babel"" but as I have shown in the video below, all the files I need for the project are present. I've reached out for help and the SCR could also not seem to know the issue. If possible may my code be approved and this weird turn of events be overlooked

https://github.com/Chimoneg27/Math-Magicians-React-App/assets/106396944/bf137466-5d41-4c8e-b14f-8081e0633e06

### CODE REVIEW

**Comment by Reem-lab** [comment]
hello @Chimoneg27 Did you check this article? https://stackoverflow.com/questions/64461003/eslint-with-babel-plugin-proposal-class-properties-not-found-declared-in-eslin

**Comment by Chimoneg27** [comment]
> hello @Chimoneg27 Did you check this article? https://stackoverflow.com/questions/64461003/eslint-with-babel-plugin-proposal-class-properties-not-found-declared-in-eslin


> hello @Chimoneg27 Did you check this article? https://stackoverflow.com/questions/64461003/eslint-with-babel-plugin-proposal-class-properties-not-found-declared-in-eslin

I'll check it out.

**Review by V-Blaze — CHANGES_REQUESTED** [review]
Hi @Chimoneg27 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

dcentl8-9b96e129-9725-401b-ac34-2feb990202a0

## Invalid Code Review Request

## You have submitted a project, that has a failed linter check. try updating the content of your `eslintrc.json` to this https://github.com/microverseinc/linters-config/blob/master/react-redux/.eslintrc.json and it should fox your error.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by Reem-lab — APPROVED** [review]
# Hi @Chimoneg27,  👋🏻👋🏻

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


## Highlights

- [ ]  Followed Gitflow 💯
- [ ]  Descriptive PR⭐
- [ ]  Kudos for working on the component🤩
- [ ]  No Linters error ✅
- [ ] Professional README 🚀




## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
